global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "dragonfly"
    static_configs:
      - targets: ["dragonfly:6379"]
    metrics_path: "/metrics"

  - job_name: "postgres"
    static_configs:
      - targets: ["postgres-exporter:9187"]

  - job_name: "virtualqueue-api"
    static_configs:
      - targets: ["host.docker.internal:9464"]
    metrics_path: "/metrics"
