{
 "title": "VirtualQueue",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Heap Used Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_memory_usage_bytes{type=\"heapUsed\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Process RSS Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_memory_usage_bytes{type=\"rss\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Process CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "process_cpu_usage_percentage{job=\"virtualqueue-api\"}",
     "legendFormat": "Process CPU Usage"
    }
   ]
  },
  {
   "title": "System Used Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "system_memory_usage{type=\"used\"}",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}